### ISSUE TITLE
Allow to scan specific files/dirs

### ISSUE THREAD

**Issue by gsantner** [djdefi/gitavscan#20]
hey, it would be cool to if it also scanning specific files/dirs in jobs would be possible. 

For example, my workflow builds something, fetched dependencies from wherever, and there is a final binary there.  
I'm not really interested in scanning the git history, more on what gets into from external.  
As post-build step I would like to add a `scan "dist/" folder with clamav` step then.

**Comment by gionn** [comment]
Hello, we need to support an use case very similar to the one described here, @djdefi are PRs welcome on this topic?

**Comment by djdefi** [comment]
@gionn yes, I'd be happy to review a pull request for such a feature. Cheers!
